# Generated by Django 2.0.1 on 2018-03-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20180312_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='ibu',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
