# Generated by Django 2.0.1 on 2018-03-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_auto_20180313_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
