# Generated by Django 2.0.1 on 2018-03-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_beerlearning_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerlearning',
            name='melon',
            field=models.IntegerField(default=0),
        ),
    ]
