# Generated by Django 2.0.1 on 2018-03-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_draughtpicksuser_recent_beers_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draughtpicksuser',
            name='recent_beers',
        ),
    ]
