# Generated by Django 2.0.1 on 2018-03-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20180204_2209'),
        ('users', '0004_remove_draughtpicksuser_recent_beers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draughtpicksuser',
            name='recent_beers_new',
        ),
        migrations.AddField(
            model_name='draughtpicksuser',
            name='recent_beers',
            field=models.ManyToManyField(related_name='recent_beers', through='beers.RecentBeer', to='beers.Beer'),
        ),
    ]
