# Generated by Django 2.0.1 on 2018-03-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0012_recommendedbeer'),
        ('users', '0007_auto_20180318_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='draughtpicksuser',
            name='recommended_beers',
            field=models.ManyToManyField(related_name='recommended_beers', through='beers.RecommendedBeer', to='beers.Beer'),
        ),
    ]
